name: Deniz Durumu Verisi Guncelleme

on:
  schedule:
    - cron: '0 7 * * *'  # Her gün 07:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gereken kütüphaneleri yükle
        run: |
          pip install requests beautifulsoup4

      - name: veriler.json dosyasını olustur
        run: python main.py

      - name: Değişiklikleri Commit Et
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Otomatik: veriler.json güncellendi"
          branch: main
          file_pattern: veriler.json
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
